n_train = -1
verbose = false
report_to = "/local/scratch/$USER/experiments/biobench"

[data]
# Benchmark
beluga = "/research/nfs_su_809/workspace/stevens.994/datasets/beluga"
fishnet = "/research/nfs_su_809/workspace/stevens.994/datasets/fishnet"
# fungiclef = "/research/nfs_su_809/workspace/stevens.994/datasets/fungiclef"
herbarium19 = "/research/nfs_su_809/workspace/stevens.994/datasets/herbarium19"
iwildcam = "/research/nfs_su_809/workspace/stevens.994/datasets/iwildcam"
kabr = "/research/nfs_su_809/workspace/stevens.994/datasets/kabr"
# mammalnet = "/research/nfs_su_809/workspace/stevens.994/datasets/mammalnet"
plankton = "/research/nfs_su_809/workspace/stevens.994/datasets/plankton"
plantnet = "/research/nfs_su_809/workspace/stevens.994/datasets/plantnet"

# Prior work
imagenet1k = "huggingface"
inat21 = "/research/nfs_su_809/workspace/stevens.994/datasets/inat21"
newt = "/research/nfs_su_809/workspace/stevens.994/datasets/newt"

[[models]]
org = "vjepa"
ckpt = "vitl16"

[[models]]
org = "vjepa"
ckpt = "vith16"

[[models]]
org = "open-clip"
ckpt = "ViT-B-32/openai"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16/openai"

[[models]]
org = "open-clip"
ckpt = "ViT-L-14/openai"

[[models]]
org = "open-clip"
ckpt = "ViT-L-14-336/openai"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16-SigLIP/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-256/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-384/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-512/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-L-16-SigLIP-256/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-L-16-SigLIP-384/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-SO400M-14-SigLIP/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-SO400M-14-SigLIP-384/webli"

[[models]]
org = "timm"
ckpt = "efficientnet_b0.ra_in1k"

[[models]]
org = "timm"
ckpt = "efficientnet_b3.ra2_in1k"

[[models]]
org = "timm"
ckpt = "mobilenetv2_100.ra_in1k"

[[models]]
org = "timm"
ckpt = "mobilenetv3_large_100.ra_in1k"

[[models]]
org = "timm"
ckpt = "resnet18d.ra2_in1k"

[[models]]
org = "timm"
ckpt = "resnet18.a1_in1k"

[[models]]
org = "timm"
ckpt = "resnet50d.a1_in1k"

[[models]]
org = "timm"
ckpt = "resnet50.a1_in1k"

[[models]]
org = "timm"
ckpt = "convnext_tiny.in12k"

[[models]]
org = "timm"
ckpt = "convnext_tiny.in12k_ft_in1k"

[[models]]
org = "timm"
ckpt = "vit_base_patch16_224.augreg2_in21k_ft_in1k"

[[models]]
org = "dinov2"
ckpt = "dinov2_vits14_reg"

[[models]]
org = "dinov2"
ckpt = "dinov2_vitb14_reg"

[[models]]
org = "dinov2"
ckpt = "dinov2_vitl14_reg"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-large-patch14-224"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-large-patch14-336"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-large-patch14-448"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-huge-patch14-224"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-huge-patch14-336"

[[models]]
org = "open-clip"
ckpt = "hf-hub:imageomics/bioclip"

[[models]]
org = "dinov2"
ckpt = "dinov2_vitg14_reg"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-huge-patch14-448"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-1B-patch14-224"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-1B-patch14-336"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-1B-patch14-448"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-3B-patch14-224"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-3B-patch14-336"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-3B-patch14-448"

[[models]]
org = "sam2"
ckpt = "sam2_hiera_tiny.fb_r896_2pt1"

[[models]]
org = "sam2"
ckpt = "sam2_hiera_small.fb_r896_2pt1"

[[models]]
org = "sam2"
ckpt = "sam2_hiera_base_plus.fb_r896_2pt1"

[[models]]
org = "sam2"
ckpt = "sam2_hiera_large.fb_r1024_2pt1"

[[models]]
org = "vjepa"
ckpt = "vith16-384"

