n_train = [3, 10, 30, 100, 300, 1000, -1]

[data]
newt = "/research/nfs_su_809/workspace/stevens.994/datasets/newt"
plankton = "/research/nfs_su_809/workspace/stevens.994/datasets/plankton"
# herbarium19 = "/research/nfs_su_809/workspace/stevens.994/datasets/herbarium19"
# inat21 = "/research/nfs_su_809/workspace/stevens.994/datasets/inat21"
# kabr = "/research/nfs_su_809/workspace/stevens.994/datasets/kabr"
iwildcam = "/research/nfs_su_809/workspace/stevens.994/datasets/iwildcam"
# plantnet = "/research/nfs_su_809/workspace/stevens.994/datasets/plantnet"
# mammalnet = "/research/nfs_su_809/workspace/stevens.994/datasets/mammalnet"
fishnet = "/research/nfs_su_809/workspace/stevens.994/datasets/fishnet"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16/openai"

[[models]]
org = "open-clip"
ckpt = "ViT-L-14/openai"

[[models]]
org = "open-clip"
ckpt = "ViT-L-14-336/openai"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16-SigLIP/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-256/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-384/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-B-16-SigLIP-512/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-L-16-SigLIP-256/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-L-16-SigLIP-384/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-SO400M-14-SigLIP/webli"

[[models]]
org = "open-clip"
ckpt = "ViT-SO400M-14-SigLIP-384/webli"

[[models]]
org = "timm"
ckpt = "efficientnet_b3.ra2_in1k"

[[models]]
org = "timm"
ckpt = "mobilenetv3_large_100.ra_in1k"

[[models]]
org = "timm"
ckpt = "resnet18d.ra2_in1k"

[[models]]
org = "timm"
ckpt = "resnet18.a1_in1k"

[[models]]
org = "timm"
ckpt = "resnet50d.a1_in1k"

[[models]]
org = "dinov2"
ckpt = "dinov2_vits14_reg"

[[models]]
org = "dinov2"
ckpt = "dinov2_vitb14_reg"

[[models]]
org = "dinov2"
ckpt = "dinov2_vitl14_reg"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-large-patch14-224"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-large-patch14-336"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-large-patch14-448"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-huge-patch14-224"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-huge-patch14-336"

[[models]]
org = "aimv2"
ckpt = "apple/aimv2-huge-patch14-448"

# [[models]]
# org = "dinov2"
# ckpt = "dinov2_vitg14_reg"

[[models]]
org = "open-clip"
ckpt = "hf-hub:imageomics/bioclip"

